services:
  app:
    build: .
    command:
      - bash
      - -c
      - |
        coldfront migrate
        coldfront runserver 0:8000
    environment:
      - DEBUG=True
      - DB_URL=sqlite:////db/coldfront.db
      - OIDC_OP_JWKS_ENDPOINT
      - OIDC_RP_SIGN_ALGO
      - OIDC_RP_CLIENT_ID
      - OIDC_RP_CLIENT_SECRET
      - OIDC_OP_AUTHORIZATION_ENDPOINT
      - OIDC_OP_TOKEN_ENDPOINT
      - OIDC_OP_USER_ENDPOINT
      - "OIDC_RP_SCOPES=openid email profile User.Read"
      - PLUGIN_AUTH_OIDC
      - PLUGIN_ICL=True
    volumes:
      - ./local_settings.py:/etc/coldfront/local_settings.py:ro
      - ./imperial_coldfront_plugin/:/usr/src/imperial_coldfront_plugin/
      - ./:/usr/src/app/
      - db:/db
    ports:
      - 127.0.0.1:8000:8000
volumes:
  db:
