services:
  app:
    build: .
    command:
      - bash
      - -c
      - |
        if [ "${ENABLE_LOCAL_LDAP:-}" = "True" ]; then
          export LDAP_PASSWORD=coldfront-local
          export LDAP_USERNAME=cn=admin,dc=ic,dc=ac,dc=uk
          export LDAP_URI=ldap://ldap:389
          export LDAP_USER_OU=ou=Users,ou=Imperial College (London),dc=ic,dc=ac,dc=uk
          export LDAP_GROUP_OU=ou=RCS,ou=Groups,ou=Imperial College (London),dc=ic,dc=ac,dc=uk
        fi
        coldfront migrate
        coldfront qcluster &
        coldfront runserver 0:8000
    environment:
      - DEBUG=True
      - DB_URL=sqlite:////db/coldfront.db
      - OIDC_OP_JWKS_ENDPOINT=https://login.microsoftonline.com/2b897507-ee8c-4575-830b-4f8267c3d307/discovery/v2.0/keys
      - OIDC_RP_SIGN_ALGO=RS256
      - OIDC_RP_CLIENT_ID
      - OIDC_RP_CLIENT_SECRET
      - OIDC_OP_AUTHORIZATION_ENDPOINT=https://login.microsoftonline.com/2b897507-ee8c-4575-830b-4f8267c3d307/oauth2/v2.0/authorize
      - OIDC_OP_TOKEN_ENDPOINT=https://login.microsoftonline.com/2b897507-ee8c-4575-830b-4f8267c3d307/oauth2/v2.0/token
      - OIDC_OP_USER_ENDPOINT=https://graph.microsoft.com/oidc/userinfo
      - "OIDC_RP_SCOPES=openid email profile User.Read"
      - MICROSOFT_TENANT_ID=2b897507-ee8c-4575-830b-4f8267c3d307
      - PLUGIN_AUTH_OIDC
      - PLUGIN_ICL=True
      - GPFS_API_URL=https://gpfs-dev-1.hpc.ic.ac.uk/scalemgmt/v2/
      - GPFS_API_USERNAME
      - GPFS_API_PASSWORD
      - GPFS_API_VERIFY=False
      - GPFS_FILESYSTEM_NAME=gpfs
      - GPFS_FILESYSTEM_MOUNT_PATH=/ibm
      - GPFS_FILESYSTEM_TOP_LEVEL_DIRECTORIES=
      - ENABLE_LOCAL_LDAP
      - LDAP_PASSWORD
      - LDAP_USERNAME
      - LDAP_URI
      - LDAP_USER_OU
      - LDAP_GROUP_OU
      - SHOW_CREDIT_BALANCE
      - ENABLE_RDF_ALLOCATION_LIFECYCLE
      - ENABLE_USER_GROUP_CREATION
      - RDF_ASK_TICKET_URL
      - RDF_ACCESS_POLICY_URL
      - ENABLE_RDF_ALLOCATION_AUTO_CREDIT
    volumes:
      - ./local_settings.py:/etc/coldfront/local_settings.py:ro
      - ./imperial_coldfront_plugin/:/usr/src/imperial_coldfront_plugin/
      - ./coldfront_overrides/static/:/usr/share/coldfront/site/static/
      - ./:/usr/src/app/
      - db:/db
    depends_on:
      ldap:
        condition: service_healthy
    ports:
      - 127.0.0.1:8000:8000
  ldap:
    build: ./openldap
    environment:
      LDAP_ADMIN_PASSWORD: coldfront-local
    volumes:
      - ldap:/var/lib/ldap
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-H", "ldap://localhost:389", "-D", "cn=admin,dc=ic,dc=ac,dc=uk", "-w", "coldfront-local", "-b", "dc=ic,dc=ac,dc=uk", "-s", "base"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
volumes:
  db:
  ldap:
